### ISSUE TITLE
Issue reported with Seaborn Pairgrid

### ISSUE THREAD

**Issue by bryevdv** [mpld3/mplexporter#34]
Originally reported here: https://github.com/ContinuumIO/bokeh/issues/1283

**Comment by joelostblom** [comment]
are there any updates on this issue? I made a minimal example using a sample from the seaborn gallery http://nbviewer.ipython.org/github/joelostblom/test_ipynbs/blob/master/bokeh_seaborn_pairgrid.ipynb. I tried passing a matplotlib.figure.Figure object, but it didn't work.

**Comment by aflaxman** [comment]
Here is a version with just my suggestion of using `fig=plt.gcf()`:

```
import seaborn as sns
sns.set_style('white')

from bokeh import mpl
import matplotlib.pyplot as plt

%matplotlib inline

df = sns.load_dataset("iris")
pp = sns.pairplot(df, hue="species")

mpl.to_bokeh(fig=plt.gcf())
```

For me, it raises a `NotImplementedError` in `bokeh`, which I think is what you find as well.  Therefore, I think that this is an issue to raise in the https://github.com/bokeh/bokeh project.  Please reopen if there is something that needs to change in `mplexporter`.

**Comment by aflaxman** [comment]
Here is a version which produces an interactive plot with `mpld3`:

```
import matplotlib.pyplot as plt, seaborn as sns, mpld3
%matplotlib inline
sns.set_style('white')


df = sns.load_dataset("iris")
pp = sns.pairplot(df, hue="species")

mpld3.display()
```

**Comment by joelostblom** [comment]
Thanks for the quick response, I posted back in the original issue in [Bokeh](https://github.com/bokeh/bokeh/issues/1283)
